### ISSUE TITLE
canary_tag feature from Nomad 0.8.4 causing job submit failure.

### ISSUE THREAD

**Issue by d4rk8l1tz** [terraform-providers/terraform-provider-nomad#44] opened 2018-09-04 11:08 UTC
Our setup is like this:
We have a git repo managing job files for various teams which uses terraform to push the jobs into nomad on build.
We want to leverage the latest(nomad 0.8.4) `canary_tags` option in the service stanza of the job file.
Now when i use nomad to push the file directly it works but i cannot do the same using terraform

```
nomad_job.xyz: error parsing jobspec: error parsing 'job': 1 error(s) occurred:
group: 'services-central', task: 'xyz', service (0) -> invalid key: canary_tags
```

It looks like the nomad jobspec being used in this repo needs an update to have the latest changes from nomad.
cc @MisterSerious

**Comment by sam-myers** [comment] 2018-09-25 00:31
Similarly, `progress_deadline` from the `update` stanza is not recognized either.

**Comment by d4rk8l1tz** [comment] 2018-10-04 06:32
So i fixed this locally by building the provider with the latest jobspec from nomad, hope this is fixed soon here too.

**Comment by epetrovich** [comment] 2018-11-06 13:41
* group: 'blitzops-group' -> invalid key: reschedule

**Comment by mildred** [comment] 2018-11-07 10:30
Duplicate of #46 ?

**Comment by cgbaker** [comment] 2018-11-28 12:29
closing this as a dupe, will track in #46

**Closed by cgbaker** 2018-11-28 12:29 UTC
