### ISSUE TITLE
Nomad provider + migrate block

### ISSUE THREAD

**Issue by yellowmegaman** [terraform-providers/terraform-provider-nomad#43] opened 2018-08-21 07:42 UTC
Hi there, I'm currently on TF 0.11.7 and nomad provider 1.2.0.

Any news on when nomad provider will support `migrate` block?

And also would be great to know how to find compatibility list of some kind, right now everything is empirical =)

Thanks a lot in advance! Provider is awesome, already being able to deploy everything via terraform, which is huge.

**Comment by shantanugadgil** [comment] 2018-08-21 08:48
I too have been waiting for the new version of the provider to be released!

**Comment by lawliet89** [comment] 2018-09-04 08:43
I think this can be "enabled" by updating the vendored Nomad Go package.

**Comment by mildred** [comment] 2018-11-07 10:31
duplicate of #46 ?

**Comment by cgbaker** [comment] 2018-11-28 12:29
closing this as a dupe, will track in #46

**Closed by cgbaker** 2018-11-28 12:29 UTC
